export default [
  { country: "ANDORRA", code: "376" },
  { country: "UNITED ARAB EMIRATES", code: "971" },
  { country: "AFGHANISTAN", code: "93" },
  { country: "ALBANIA", code: "355" },
  { country: "ARMENIA", code: "374" },
  { country: "NETHERLANDS ANTILLES", code: "599" },
  { country: "ANGOLA", code: "244" },
  { country: "ANTARCTICA", code: "672" },
  { country: "ARGENTINA", code: "54" },
  { country: "AUSTRIA", code: "43" },
  { country: "AUSTRALIA", code: "61" },
  { country: "ARUBA", code: "297" },
  { country: "AZERBAIJAN", code: "994" },
  { country: "BOSNIA AND HERZEGOVINA", code: "387" },
  { country: "BANGLADESH", code: "880" },
  { country: "BELGIUM", code: "32" },
  { country: "BURKINA FASO", code: "226" },
  { country: "BULGARIA", code: "359" },
  { country: "BAHRAIN", code: "973" },
  { country: "BURUNDI", code: "257" },
  { country: "BENIN", code: "229" },
  { country: "SAINT BARTHELEMY", code: "590" },
  { country: "BRUNEI DARUSSALAM", code: "673" },
  { country: "BOLIVIA", code: "591" },
  { country: "BRAZIL", code: "55" },
  { country: "BHUTAN", code: "975" },
  { country: "BOTSWANA", code: "267" },
  { country: "BELARUS", code: "375" },
  { country: "BELIZE", code: "501" },
  { country: "CANADA", code: "1" },
  { country: "COCOS (KEELING) ISLANDS", code: "61" },
  { country: "CONGO, THE DEMOCRATIC REPUBLIC OF THE", code: "243" },
  { country: "CENTRAL AFRICAN REPUBLIC", code: "236" },
  { country: "CONGO", code: "242" },
  { country: "SWITZERLAND", code: "41" },
  { country: "COTE D IVOIRE", code: "225" },
  { country: "COOK ISLANDS", code: "682" },
  { country: "CHILE", code: "56" },
  { country: "CAMEROON", code: "237" },
  { country: "CHINA", code: "86" },
  { country: "COLOMBIA", code: "57" },
  { country: "COSTA RICA", code: "506" },
  { country: "CUBA", code: "53" },
  { country: "CAPE VERDE", code: "238" },
  { country: "CHRISTMAS ISLAND", code: "61" },
  { country: "CYPRUS", code: "357" },
  { country: "CZECH REPUBLIC", code: "420" },
  { country: "GERMANY", code: "49" },
  { country: "DJIBOUTI", code: "253" },
  { country: "DENMARK", code: "45" },
  { country: "ALGERIA", code: "213" },
  { country: "ECUADOR", code: "593" },
  { country: "ESTONIA", code: "372" },
  { country: "EGYPT", code: "20" },
  { country: "ERITREA", code: "291" },
  { country: "SPAIN", code: "34" },
  { country: "ETHIOPIA", code: "251" },
  { country: "FINLAND", code: "358" },
  { country: "FIJI", code: "679" },
  { country: "FALKLAND ISLANDS (MALVINAS)", code: "500" },
  { country: "MICRONESIA, FEDERATED STATES OF", code: "691" },
  { country: "FAROE ISLANDS", code: "298" },
  { country: "FRANCE", code: "33" },
  { country: "GABON", code: "241" },
  { country: "UNITED KINGDOM", code: "44" },
  { country: "GEORGIA", code: "995" },
  { country: "GHANA", code: "233" },
  { country: "GIBRALTAR", code: "350" },
  { country: "GREENLAND", code: "299" },
  { country: "GAMBIA", code: "220" },
  { country: "GUINEA", code: "224" },
  { country: "EQUATORIAL GUINEA", code: "240" },
  { country: "GREECE", code: "30" },
  { country: "GUATEMALA", code: "502" },
  { country: "GUINEA-BISSAU", code: "245" },
  { country: "GUYANA", code: "592" },
  { country: "HONG KONG", code: "852" },
  { country: "HONDURAS", code: "504" },
  { country: "CROATIA", code: "385" },
  { country: "HAITI", code: "509" },
  { country: "HUNGARY", code: "36" },
  { country: "INDONESIA", code: "62" },
  { country: "IRELAND", code: "353" },
  { country: "ISRAEL", code: "972" },
  { country: "ISLE OF MAN", code: "44" },
  { country: "INDIA", code: "91" },
  { country: "IRAQ", code: "964" },
  { country: "IRAN, ISLAMIC REPUBLIC OF", code: "98" },
  { country: "ICELAND", code: "354" },
  { country: "ITALY", code: "39" },
  { country: "JORDAN", code: "962" },
  { country: "JAPAN", code: "81" },
  { country: "KENYA", code: "254" },
  { country: "KYRGYZSTAN", code: "996" },
  { country: "CAMBODIA", code: "855" },
  { country: "KIRIBATI", code: "686" },
  { country: "COMOROS", code: "269" },
  { country: "KOREA DEMOCRATIC PEOPLES REPUBLIC OF", code: "850" },
  { country: "KOREA REPUBLIC OF", code: "82" },
  { country: "KUWAIT", code: "965" },
  { country: "KAZAKSTAN", code: "7" },
  { country: "LAO PEOPLES DEMOCRATIC REPUBLIC", code: "856" },
  { country: "LEBANON", code: "961" },
  { country: "LIECHTENSTEIN", code: "423" },
  { country: "SRI LANKA", code: "94" },
  { country: "LIBERIA", code: "231" },
  { country: "LESOTHO", code: "266" },
  { country: "LITHUANIA", code: "370" },
  { country: "LUXEMBOURG", code: "352" },
  { country: "LATVIA", code: "371" },
  { country: "LIBYAN ARAB JAMAHIRIYA", code: "218" },
  { country: "MOROCCO", code: "212" },
  { country: "MONACO", code: "377" },
  { country: "MOLDOVA, REPUBLIC OF", code: "373" },
  { country: "MONTENEGRO", code: "382" },
  { country: "MADAGASCAR", code: "261" },
  { country: "MARSHALL ISLANDS", code: "692" },
  { country: "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF", code: "389" },
  { country: "MALI", code: "223" },
  { country: "MYANMAR", code: "95" },
  { country: "MONGOLIA", code: "976" },
  { country: "MACAU", code: "853" },
  { country: "MAURITANIA", code: "222" },
  { country: "MALTA", code: "356" },
  { country: "MAURITIUS", code: "230" },
  { country: "MALDIVES", code: "960" },
  { country: "MALAWI", code: "265" },
  { country: "MEXICO", code: "52" },
  { country: "MALAYSIA", code: "60" },
  { country: "MOZAMBIQUE", code: "258" },
  { country: "NAMIBIA", code: "264" },
  { country: "NEW CALEDONIA", code: "687" },
  { country: "NIGER", code: "227" },
  { country: "NIGERIA", code: "234" },
  { country: "NICARAGUA", code: "505" },
  { country: "NETHERLANDS", code: "31" },
  { country: "NORWAY", code: "47" },
  { country: "NEPAL", code: "977" },
  { country: "NAURU", code: "674" },
  { country: "NIUE", code: "683" },
  { country: "NEW ZEALAND", code: "64" },
  { country: "OMAN", code: "968" },
  { country: "PANAMA", code: "507" },
  { country: "PERU", code: "51" },
  { country: "FRENCH POLYNESIA", code: "689" },
  { country: "PAPUA NEW GUINEA", code: "675" },
  { country: "PHILIPPINES", code: "63" },
  { country: "PAKISTAN", code: "92" },
  { country: "POLAND", code: "48" },
  { country: "SAINT PIERRE AND MIQUELON", code: "508" },
  { country: "PITCAIRN", code: "870" },
  { country: "PUERTO RICO", code: "1" },
  { country: "PORTUGAL", code: "351" },
  { country: "PALAU", code: "680" },
  { country: "PARAGUAY", code: "595" },
  { country: "QATAR", code: "974" },
  { country: "ROMANIA", code: "40" },
  { country: "SERBIA", code: "381" },
  { country: "RUSSIAN FEDERATION", code: "7" },
  { country: "RWANDA", code: "250" },
  { country: "SAUDI ARABIA", code: "966" },
  { country: "SOLOMON ISLANDS", code: "677" },
  { country: "SEYCHELLES", code: "248" },
  { country: "SUDAN", code: "249" },
  { country: "SWEDEN", code: "46" },
  { country: "SINGAPORE", code: "65" },
  { country: "SAINT HELENA", code: "290" },
  { country: "SLOVENIA", code: "386" },
  { country: "SLOVAKIA", code: "421" },
  { country: "SIERRA LEONE", code: "232" },
  { country: "SAN MARINO", code: "378" },
  { country: "SENEGAL", code: "221" },
  { country: "SOMALIA", code: "252" },
  { country: "SURINAME", code: "597" },
  { country: "SAO TOME AND PRINCIPE", code: "239" },
  { country: "EL SALVADOR", code: "503" },
  { country: "SYRIAN ARAB REPUBLIC", code: "963" },
  { country: "SWAZILAND", code: "268" },
  { country: "CHAD", code: "235" },
  { country: "TOGO", code: "228" },
  { country: "THAILAND", code: "66" },
  { country: "TAJIKISTAN", code: "992" },
  { country: "TOKELAU", code: "690" },
  { country: "TIMOR-LESTE", code: "670" },
  { country: "TURKMENISTAN", code: "993" },
  { country: "TUNISIA", code: "216" },
  { country: "TONGA", code: "676" },
  { country: "TURKEY", code: "90" },
  { country: "TUVALU", code: "688" },
  { country: "TAIWAN, PROVINCE OF CHINA", code: "886" },
  { country: "TANZANIA, UNITED REPUBLIC OF", code: "255" },
  { country: "UKRAINE", code: "380" },
  { country: "UGANDA", code: "256" },
  { country: "UNITED STATES", code: "1" },
  { country: "URUGUAY", code: "598" },
  { country: "UZBEKISTAN", code: "998" },
  { country: "HOLY SEE (VATICAN CITY STATE)", code: "39" },
  { country: "VENEZUELA", code: "58" },
  { country: "VIET NAM", code: "84" },
  { country: "VANUATU", code: "678" },
  { country: "WALLIS AND FUTUNA", code: "681" },
  { country: "SAMOA", code: "685" },
  { country: "KOSOVO", code: "381" },
  { country: "YEMEN", code: "967" },
  { country: "MAYOTTE", code: "262" },
  { country: "SOUTH AFRICA", code: "27" },
  { country: "ZAMBIA", code: "260" },
  { country: "ZIMBABWE", code: "263" },
];
